services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: parking
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_LOG_DESTINATION: stderr
      POSTGRES_LOGGING_COLLECTOR: on
      POSTGRES_LOG_DIRECTORY: /var/log/postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./logs:/var/log/postgresql

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
